[tools]
java = "corretto-21.0.10.7.1"
clojure = "1.12.4.1602"
babashka = "1.12.214"
clj-kondo = "2026.01.19"
cljstyle = "0.17.642"


[env]
JAVA_TOOL_OPTIONS = """
-Dorg.slf4j.simpleLogger.defaultLogLevel=info
-Dorg.slf4j.simpleLogger.showDateTime=true
-Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
-Dorg.slf4j.simpleLogger.showThreadName=true
-Xms128m -Xmx1024m
"""
